### ISSUE TITLE
Zeitstempel im P, V und L File

### ISSUE THREAD

**Issue by CosmicLabDESY** [CosmicLabDESY/muonic#11]
Bitte darauf achten, dass in allen drei Fils ein sinnvoller, für Schüler verwendbarer Zeitstempel ausgegeben wird.

**Comment by martinohmann** [comment]
Wie ist das gemeint? Geht es hier um den Zeitstempel, der in den "start/stopp"-Kommentaren geschrieben wird, oder um Zeitstempel, die vor jede geschriebene Datenzeile gesetzt werden? Bei zweiterem bräuchte ich dann ein passendes Format, UNIX-Timestamps würden sich anbieten, da man diese leicht maschinell auswerten kann.

**Comment by caroschwerdt** [comment]
Es ist der Zeitstempel gemeint, der bei jedem Start/Stopp.Kommentar verwendet wird. 
Ich dachte eher, dass wir diskutieren, ob UTC oder CTE? 

Ich würde solch einen Zeitstempel gut finden: Fr 13. Feb 2016 23:31:30 UTC

Da auf den Rechnern ja immer CTE agezeigt wird, ist es für die Schüler wahrscheinlich einfacher CTE-Zeiten im File zuzuordnen.?.

Darüber hinaus wäre es auch gut die Struktur des R, V und L file anzupassen. 
Vorschlag: Zeitstempel (also, wann das Event passtiert ist) | Eventinfo (Rate oder gemessene Lebensdauer oder gemessene Zeitunterschied) 
Der Zeitstempel sollte dann vortlaufend sein, also Start-Kommentar ist Zeitpunkt null.
Im R wären das dann sekunden
im V ns? oder s?
im L ns

**Comment by CosmicLabDESY** [comment]
Wir haben nochmal überlegt und wünschen uns folgendes:
0) Zeitstempel auf UTC beziehen
1) Zeitstempel im Start-/Stopp-Kommentar: Fr 13. Feb 2016 23:31:30
2) Zeitstempel in jeder Zeile/zu jedem Event:
Jahr Monat Tag Stunde Minute Sekunde Millisekunde Eventinfo
Bsp: 2016 06 02 09 45 30 05 Eventinfo

**Comment by hpbretz** [comment]
Zeitstempel sind jetzt alle auf UTC bezogen. Die Zeitstempel in den Pulsefiles werden aus den jeweiligen Zeilen der DAQ berechnet. Diese können nur dann in eine absolute Zeit pro Pulsefileeintrag umgerechnet werden, wenn ein GPS angeschlossen ist. Ansonsten wird eine relative Zeit in Sekunden in Bezug auf die Messung berechnet. Deswegen haben wir uns dafür entschieden, den "%Y-%m-%d %H:%M:%S.%f" Zeitstempel hier nicht zu benutzen.

Die anderen Zeitstempel können in Python wie folgt eingelesen werden

from datetime import datetime
event_time = datetime.strptime(' '.join(line.split(' ')[:2]), "%Y-%m-%d %H:%M:%S.%f")

wenn line eine Zeile des Files als String ist.

**Comment by CosmicLabDESY** [comment]
Bitte anderen Weg finden, um Zeitstempel im P-File zu integrieren.
