### ISSUE TITLE
Fit

### ISSUE THREAD

**Issue by CosmicLabDESY** [CosmicLabDESY/muonic#16]
Unter Velocity und Lifetime wäre es toll, wenn die Fitfunktion ausgegeben werden könnte.

Der Mittelwert (Velocity) bzw. die mittlere Lebensdauer (Lifetime) können wie gehabt im Diagramm in einer Box ausgespuckt werden (so kann man das Diagramm mit Wert in einem Bild speichern). Auch wäre es aber gut alle Fitparameter in einem Kästchen daneben auszuspucken. bitte auch in Textform, so können die Werte leicht per copy and paste kopiert werden.

**Comment by hpbretz** [comment]
In der aktuellen Änderung wird als Fitfunktion pauschal eine quadratische Funktion angezeigt, je nach Fit ist es aber eine Exponentialfunktion oder eine Gaußfunktion.
