### ISSUE TITLE
Puls Analyzer

### ISSUE THREAD

**Issue by CosmicLabDESY** [CosmicLabDESY/muonic#2]
Ein Pulsdiagramm für jeden Channel wird gebraucht. Das Oscilloscope kann weg. Es sollte jedes Pulsdiagramm einzeln (als Bild) speicherbar sein.
![7a2edc30-dafb-11e5-97a2-9421d92555d9](https://cloud.githubusercontent.com/assets/17313229/14141611/7cb6d976-f680-11e5-9a44-2776ede7684f.png)

**Comment by hpbretz** [comment]
In https://github.com/CosmicLabDESY/muonic/commit/795ea5f320eeb6b0015dafe37b419b45f18bc910 eingeführt und mit Detektoren getestet.
