### ISSUE TITLE
Icon für Muonic

### ISSUE THREAD

**Issue by CosmicLabDESY** [CosmicLabDESY/muonic#20]
Das wünschen wir uns, damit unter den offenen ubuntu-Fenstern nicht immer Muonic als Fragezeichen auftaucht (graues Logo mit Fragezeichen in der Menüleiste links). Layout können wir uns überlegen, was sind die Anforderungen?

**Comment by CosmicLabDESY** [comment]
Ich habe ein Icon:
![muon](https://cloud.githubusercontent.com/assets/17313229/19183622/82fae040-8c79-11e6-8804-296dd657b417.png)

**Comment by CosmicLabDESY** [comment]
Credit: The Particle Zoo http://www.particlezoo.net.

**Comment by CosmicLabDESY** [comment]
Wenn möglich, den Hintergrund in Transparent machen (also nur den Kreis sammt Inhalt als Icon verwenden).

**Comment by hpbretz** [comment]
Wie sieht es mit den Rechten an dem Bild aus?

**Comment by hpbretz** [comment]
Hab mal ein Icon eingefügt, wir müssen uns das mal auf Ubuntu anschauen ob es so aussieht wie gewünscht.

**Comment by hpbretz** [comment]
![muoniclogo](https://cloud.githubusercontent.com/assets/8876379/20006208/db2b418c-a296-11e6-89b1-85e5b8848313.png)

So schaut es jetzt aus, ich schließe den Issue mal bis auf weiteres, es sei denn es gibt noch was Kosmetisches zu ändern.
