### ISSUE TITLE
Geschwindigkeitsmessung: Fitparamter

### ISSUE THREAD

**Issue by CosmicLabDESY** [CosmicLabDESY/muonic#4]
Es wird in muonic die Standardabweichung als Fitparameter ausgegeben, wir brauchen aber den Mittelwert.

**Comment by martinohmann** [comment]
Sollte eigentlich mit 2d25fb943cd9dd7cf1afd5376de753227306a064 erledigt sein

**Comment by CosmicLabDESY** [comment]
Ja ist erledigt.
